"use client";

import { useState } from "react";
import { CLAIM_FINANCIAL_STATUS, expiryRisk, getEntitlements, getPlanFinancials } from "../../lib/domain/operations.js";
import { canClaimPlan, canEditPlan, isDashubAdmin } from "../../lib/domain/permissions.js";
import { formatMoney, parseMoneyToCents } from "../../lib/domain/money.js";
import { displayDate } from "./QuoteSummary.jsx";

const num = new Intl.NumberFormat("en-NZ");
const date = (value) => displayDate(value?.slice(0, 10));
const title = (value) => value?.replaceAll("_", " ") ?? "—";

export default function PlanDetail({ plan, actor, workspace, service, onAction, onBack, onEdit, onClaim, onInvoices }) {
  const [topUp, setTopUp] = useState("");
  const [cancellationFee, setCancellationFee] = useState("0.00");
  const [showAllPayments, setShowAllPayments] = useState(false);
  const financial = getPlanFinancials(plan);
  const entitlements = getEntitlements(plan);
  const risk = expiryRisk(plan, new Date().toISOString().slice(0, 10));
  const company = workspace.companies.find((item) => item.id === plan.dealerGroupId);
  const branch = company?.branches.find((item) => item.id === plan.branchId);
  const paymentControl = isDashubAdmin(actor) || actor.permissions?.managePayments;
  const schedule = plan.paymentSchedule ?? [];
  const visible = showAllPayments ? schedule : schedule.slice(0, 12);
  const eventRows = [
    ...schedule.flatMap((payment) => payment.attempts.map((attempt) => ({ at: attempt.at, label: `${payment.id} ${title(attempt.outcome)}`, amountCents: attempt.amountCents }))),
    ...(plan.ledger ?? []).filter((entry) => ["top_up", "dealer_shortfall", "refund"].includes(entry.type)).map((entry) => ({ at: entry.at, label: title(entry.type), amountCents: entry.amountCents })),
  ].sort((a, b) => b.at.localeCompare(a.at));

  return <>
    <div className="backRow"><button className="backButton" onClick={onBack}>← Plans</button><span className="pill">{plan.origin === "manufacturer" ? "Manufacturer · locked" : title(plan.status)}</span></div>
    <header className="pageHeader"><div><p className="eyebrow">PLAN {plan.id.toUpperCase()} · {plan.scenario ?? "SANDBOX"}</p><h1>{plan.quote.customer.firstName} {plan.quote.customer.lastName}</h1><p className="sub">{company?.name ?? "Global manufacturer"} {branch ? `· ${branch.name}` : ""} · {plan.quote.vehicle.registration || "No registration"}</p></div><div className="headerActions">{canEditPlan(actor, plan) && <button className="secondaryButton" onClick={onEdit}>Edit quote</button>}{plan.status === "quote" && company && (isDashubAdmin(actor) || actor.permissions?.activatePlans) && <button className="primaryButton" onClick={() => onAction(() => service.activate(actor, plan.id), "Sandbox contract activated and snapshotted.")}>Activate sandbox plan</button>}{canClaimPlan(actor, plan, workspace) && <button className="primaryButton" onClick={onClaim}>Claim next service</button>}</div></header>
    {risk && <p className="notice">Proposed expiry review {displayDate(risk.proposedExpiry)} ({risk.daysToExpiry} days). Forfeiture is subject to legal review and is not automatic.</p>}
    <div className="operationalGrid">
      <section className="panel"><h2>Customer</h2><dl className="detailList"><div><dt>Name</dt><dd>{plan.quote.customer.firstName} {plan.quote.customer.lastName}</dd></div><div><dt>Mobile</dt><dd>{plan.quote.customer.mobile}</dd></div><div><dt>Email</dt><dd>{plan.quote.customer.email}</dd></div><div><dt>Physical address</dt><dd>{plan.quote.customer.address}</dd></div></dl></section>
      <section className="panel"><h2>Vehicle</h2><dl className="detailList"><div><dt>Vehicle</dt><dd>{plan.quote.vehicle.year} {plan.quote.vehicle.make} {plan.quote.vehicle.model}</dd></div><div><dt>Registration</dt><dd>{plan.quote.vehicle.registration || "—"}</dd></div><div><dt>VIN</dt><dd>{plan.quote.vehicle.vin || "Unavailable"}</dd></div><div><dt>Current odometer at quote</dt><dd>{num.format(plan.quote.currentOdometer)} km</dd></div><div><dt>Predicted annual distance</dt><dd>{num.format(plan.quote.annualKm)} km</dd></div></dl></section>
    </div>
    <section className="panel sectionGap"><div className="panelHeading"><div><h2>Contract and funding</h2><p className="sub">Dashub is the contracting party. Contracted values remain fixed after activation.</p></div><span className="pill">{plan.contract ? `Revision ${plan.contract.revision}` : "Unsold quote"}</span></div><div className="compactStats"><div><span>Plan value</span><strong>{formatMoney(financial.totalCents)}</strong></div><div><span>Customer collected</span><strong>{formatMoney(financial.customerCollectedCents)}</strong></div><div><span>Available funding</span><strong>{formatMoney(financial.cashAvailableCents)}</strong></div><div><span>Remaining obligation</span><strong>{formatMoney(financial.remainingObligationCents)}</strong></div></div><p className="sub">{plan.quote.frequency} collections from {displayDate(plan.quote.firstPaymentDate)} · last quoted collection {displayDate(plan.quote.funding.finalPaymentDate)} · {plan.quote.numberOfServices} services.</p>{plan.contract && <p className="sub">Activated {date(plan.contract.activatedAt)} · setup fee {formatMoney(plan.contract.commercialTerms.setupFeeCents)} · ongoing Dashub fee {formatMoney(plan.contract.commercialTerms.ongoingFeeCents)} per claim · provider fee treatment: {plan.contract.commercialTerms.providerFeeTreatment}.</p>}</section>
    <section className="panel sectionGap"><div className="panelHeading"><div><h2>Service entitlements and predicted due points</h2><p className="sub">Only the next pending service can be claimed.</p></div>{canClaimPlan(actor, plan, workspace) && <button className="textButton" onClick={onClaim}>Open claim journey →</button>}</div><div className="tableScroll"><table><thead><tr><th>#</th><th>Service</th><th>Predicted date</th><th>Predicted km</th><th>Locked dealer value</th><th>Entitlement</th></tr></thead><tbody>{entitlements.map((item) => <tr key={item.number}><td>{item.number}</td><td><strong>{item.name}</strong><small>{item.trigger === "km" ? "Km threshold" : "Month interval"}</small></td><td>{displayDate(item.predictedDate)}</td><td>{num.format(item.predictedKm)} km</td><td>{formatMoney(item.grossCents)}</td><td><span className="pill">{item.status.toUpperCase()}</span></td></tr>)}</tbody></table></div></section>
    <section className="panel sectionGap"><div className="panelHeading"><div><h2>Payment schedule</h2><p className="sub">Sandbox actions update the local ledger. Remaining collections are capped at the contractual amount.</p></div><span className="pill">{schedule.length || plan.quote.funding.paymentCount} dates</span></div>{plan.status === "quote" ? <p className="sub">Activate the quote to simulate collections. {plan.quote.funding.paymentCount} payments are forecast.</p> : <><div className="tableScroll"><table><thead><tr><th>Date</th><th>Scheduled</th><th>Collected</th><th>Status</th><th>Sandbox action</th></tr></thead><tbody>{visible.map((payment) => <tr key={payment.id}><td>{displayDate(payment.date)}</td><td>{formatMoney(payment.amountCents)}</td><td>{formatMoney(payment.collectedCents)}</td><td>{title(payment.status)}</td><td>{paymentControl && financial.remainingObligationCents > 0 && payment.status === "scheduled" && <div className="inlineActions"><button className="textButton" onClick={() => onAction(() => service.simulatePayment(actor, plan.id, payment.id, "success"), "Scheduled collection recorded.")}>Success</button><button className="textButton dangerText" onClick={() => onAction(() => service.simulatePayment(actor, plan.id, payment.id, "failure"), "Payment failed; the plan remains active.")}>Failure</button></div>}{paymentControl && financial.remainingObligationCents > 0 && payment.status === "failed" && <button className="textButton" onClick={() => onAction(() => service.simulatePayment(actor, plan.id, payment.id, "retry_success"), "Retry succeeded; funding issue cleared.")}>Successful retry</button>}</td></tr>)}</tbody></table></div>{schedule.length > 12 && <button className="textButton sectionToggle" onClick={() => setShowAllPayments((value) => !value)}>{showAllPayments ? "Show first 12" : `Show all ${schedule.length} payments`}</button>}</>}</section>
    {plan.contract && <section className="panel sectionGap"><div className="panelHeading"><div><h2>Payment history and top-up</h2><p className="sub">Customer funds and dealer-collected shortfalls are tracked separately.</p></div></div>{paymentControl && financial.remainingObligationCents > 0 && ["active", "completed"].includes(plan.status) && <form className="inlineForm" onSubmit={(event) => { event.preventDefault(); onAction(() => service.topUp(actor, plan.id, parseMoneyToCents(topUp)), "Customer top-up recorded in sandbox."); setTopUp(""); }}><label>One-off top-up (NZD) <input type="number" min="0.01" step="0.01" value={topUp} onChange={(event) => setTopUp(event.target.value)} /></label><button className="secondaryButton">Record top-up</button><small>Maximum {formatMoney(financial.remainingObligationCents)}</small></form>}<div className="tableScroll"><table><thead><tr><th>Date</th><th>Event</th><th>Amount</th></tr></thead><tbody>{eventRows.length ? eventRows.map((item, index) => <tr key={`${item.at}-${index}`}><td>{date(item.at)}</td><td>{item.label}</td><td>{formatMoney(item.amountCents)}</td></tr>) : <tr><td colSpan="3">No payment events yet.</td></tr>}</tbody></table></div></section>}
    <section className="panel sectionGap"><div className="panelHeading"><div><h2>Claims and invoices</h2><p className="sub">One dealer invoice per claimed service and SP PO.</p></div><button className="textButton" onClick={onInvoices}>Open invoice queue →</button></div><div className="tableScroll"><table><thead><tr><th>Service</th><th>RO</th><th>Service date</th><th>SP PO</th><th>Shortfall at dealer</th><th>Invoice</th><th>Financial status</th></tr></thead><tbody>{plan.claims?.length ? plan.claims.map((claim) => <tr key={claim.id}><td>{claim.serviceNumber} {claim.earlyClaim && <span className="warningBadge">Early Claim</span>}</td><td>{claim.roNumber}</td><td>{displayDate(claim.serviceDate)}</td><td>{claim.poNumber}</td><td>{formatMoney(claim.dealerShortfallCents)}</td><td>{claim.invoice?.number ?? "Awaiting"}</td><td>{CLAIM_FINANCIAL_STATUS[claim.financialStatus] ?? title(claim.financialStatus)}</td></tr>) : <tr><td colSpan="7">No claims recorded.</td></tr>}</tbody></table></div></section>
    <div className="operationalGrid sectionGap"><section className="panel"><h2>Plan revisions</h2><p className="sub">Contract revisions are immutable snapshots and require customer consent.</p><div className="simpleRecords">{plan.revisions?.length ? plan.revisions.map((revision) => <div key={revision.number}><strong>Revision {revision.number}</strong><span>{date(revision.at)} · {revision.reason} · consent recorded</span></div>) : <p className="sub">No contract revision; quote has not been activated.</p>}</div></section><section className="panel"><h2>Audit history</h2><div className="auditScroll simpleRecords">{plan.audit?.length ? [...plan.audit].reverse().map((entry) => <div key={entry.id}><strong>{title(entry.action)}</strong><span>{date(entry.at)} · {entry.actorId} · {entry.summary}</span></div>) : <p className="sub">No audit events recorded.</p>}</div></section></div>
    {isDashubAdmin(actor) && plan.status === "active" && <section className="panel sectionGap"><h2>Sandbox cancellation</h2><p className="sub">Refund = cleared customer funds less claimed service values and cancellation fee. Setup fee is non-refundable. No real refund is sent.</p><form className="inlineForm" onSubmit={(event) => { event.preventDefault(); onAction(() => service.cancel(actor, plan.id, parseMoneyToCents(cancellationFee)), "Plan cancelled; sandbox refund recorded."); }}><label>Cancellation fee (NZD) <input type="number" min="0" step="0.01" value={cancellationFee} onChange={(event) => setCancellationFee(event.target.value)} /></label><button className="secondaryButton">Cancel sandbox plan</button></form></section>}
  </>;
}
